<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'dev',
  'SYMFONY_DOTENV_PATH' => './.env',
  'APP_SECRET' => 'ee21491504697a069007be2661f90144',
  'DATABASE_URL' => 'mysql://restaurant:restaurant@127.0.0.1:3306/restaurant?serverVersion=8.2.0&charset=utf8mb4',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
);
